
language: en

pipeline:
  - name: HFTransformersNLP
    model_weights: "/drive/My Drive/Projects/Rasa_Chatbot/bankBOT/ras/y/indic-bert-v1"
    model_name: "albert"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: char_wb
  #   min_ngram: 1
  #   max_ngram: 4
  - name: DIETClassifier
    epochs: 300
  - name: component_ner.NERv2  
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300

  - name: FallbackClassifier
    threshold: 0.1
    ambiguity_threshold: 0.01
  - name : printer.Printer  

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 300
  - name: RulePolicy
    
  

  